"""Dataset locations used by the tests.

Two datasets are exercised deliberately:

``STARTER_DATA_DIR``
    The 13-champion hand-authored sample from milestone 1. Every expected
    value in ``test_units.py`` / ``test_combat.py`` was hand-calculated
    against it, so it stays frozen -- that is precisely what makes those
    tests meaningful. It must never be regenerated by the fetch script.

``REAL_DATA_DIR``
    The live Set 17 data produced by ``scripts/fetch_cdragon.py``. It changes
    with every patch, so tests against it assert *invariants* (it loads, the
    pool conserves, matches terminate) rather than specific numbers. See
    ``test_real_dataset.py``.
"""

from __future__ import annotations

from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
STARTER_DATA_DIR = TESTS_DIR / "fixtures" / "starter_data"
REAL_DATA_DIR = TESTS_DIR.parent / "data"
